### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by SValmont** [shuryanc/megasync_aur#1]
Build fails

mega/include/mega/gfx/freeimage.h - no such file or directory

**Comment by shuryanc** [comment]
I don't have this issue. Do you have the file mega/include/mega/gfx/freeimage.h?

**Comment by Delanii** [comment]
I had the same issue.
Fortunately, fixing it was easy:

1. Find which package contains the missing file. It's this one: https://archlinux.org/packages/community/x86_64/freeimage/
2. Install the package
3. Delete failed build files (I couldn't start the build again after it failed)
4. Clone the repo and build the package again, and you should be good to go as me

I think it would be awesome to add into `PKGBUILD` a provision to check if the freeimage package is installed.
I have no experience with writing pkgbuilds, so I won't push this, but it would make the process easier.
Thank you for making this build so I can use mega again!

**Comment by SValmont** [comment]
It installs now. I might have been a dependency that I have since fixed.
